# Use an official Python runtime as a parent image
FROM python:3.10.16-slim-bookworm

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install -r /app/requirements.txt

COPY . .

# Expose the port the app runs on
EXPOSE 5500